## Preprocessing

In [382]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [383]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])

application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [384]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [385]:
# Look at APPLICATION_TYPE value counts for binning
type_count = application_df['APPLICATION_TYPE'].value_counts()
type_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [386]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = type_count[type_count<1000].index.tolist()


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: count, dtype: int64

In [387]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [388]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_count = application_df['CLASSIFICATION'].value_counts()
class_count[class_count > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [389]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_to_replace = class_count[class_count<1000].index.tolist()

# Replace in dataframe
for cls in class_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [390]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [391]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values

# drop 'IS SUCCESSFUL'
X = application_df.drop('IS_SUCCESSFUL', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [392]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [393]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1 =  50
hidden_nodes_layer2 = 45
hidden_nodes_layer3 = 30

#try new optimizer
#optimizer = RMSprop(learning_rate=0.001, decay=1e-6)
learning_rate = 0.01 
optimizer = SGD(learning_rate=learning_rate)

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)
nn.add(tf.keras.layers.Dropout(0.325))
# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu")
)
nn.add(tf.keras.layers.Dropout(0.325))

# Test 3rd layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu")
)
nn.add(tf.keras.layers.Dropout(0.325))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

/Users/katiestarnes/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/core/dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_74"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_244 (Dense)               │ (None, 50)             │         2,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_143 (Dropout)           │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_245 (Dense)               │ (None, 45)             │         2,295 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_144 (Dropout)           │ (None, 45)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_246 (Dense)               │ (None, 30)             │         1,380 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_145 (Dropout)           │ (None, 30)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_247 (Dense)               │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,756 (22.48 KB)

 Trainable params: 5,756 (22.48 KB)

 Non-trainable params: 0 (0.00 B)

In [394]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [395]:
# Train the model
#add validation split
fit_model = nn.fit(X_train_scaled, y_train, validation_split=0.155, epochs=75)

Epoch 1/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 1s 548us/step - accuracy: 0.5380 - loss: 0.7303 - val_accuracy: 0.7166 - val_loss: 0.6269
Epoch 2/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.6460 - loss: 0.6476 - val_accuracy: 0.7319 - val_loss: 0.5967
Epoch 3/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.6735 - loss: 0.6314 - val_accuracy: 0.7294 - val_loss: 0.5787
Epoch 4/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.6878 - loss: 0.6175 - val_accuracy: 0.7317 - val_loss: 0.5737
Epoch 5/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.6875 - loss: 0.6117 - val_accuracy: 0.7329 - val_loss: 0.5698
Epoch 6/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.6971 - loss: 0.6055 - val_accuracy: 0.7327 - val_loss: 0.5671
Epoch 7/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 476us/step - accuracy: 0.7019 - loss: 0.6033 - val_accuracy: 0.7345 - val_loss: 0.5648
Epoch 8/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.7033 - loss: 0.6012 - val_accuracy: 0.7350 - val_loss: 0.5619
Epoch 9/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7060 - loss: 0.6011 - val_accuracy: 0.7352 - val_loss: 0.5627
Epoch 10/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - accuracy: 0.7105 - loss: 0.5915 - val_accuracy: 0.7345 - val_loss: 0.5606
Epoch 11/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.7109 - loss: 0.5901 - val_accuracy: 0.7322 - val_loss: 0.5620
Epoch 12/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.7050 - loss: 0.5990 - val_accuracy: 0.7337 - val_loss: 0.5600
Epoch 13/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.7103 - loss: 0.5891 - val_accuracy: 0.7365 - val_loss: 0.5601
Epoch 14/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.7150 - loss: 0.5856 - val_accuracy: 0.7360 - val_loss: 0.5612
Epoch 15/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.7190 - loss: 0.5853 - val_accuracy: 0.7367 - val_loss: 0.5610
Epoch 16/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7194 - loss: 0.5815 - val_accuracy: 0.7360 - val_loss: 0.5596
Epoch 17/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - accuracy: 0.7147 - loss: 0.5868 - val_accuracy: 0.7352 - val_loss: 0.5583
Epoch 18/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7155 - loss: 0.5797 - val_accuracy: 0.7355 - val_loss: 0.5579
Epoch 19/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.7151 - loss: 0.5862 - val_accuracy: 0.7360 - val_loss: 0.5582
Epoch 20/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7129 - loss: 0.5860 - val_accuracy: 0.7355 - val_loss: 0.5571
Epoch 21/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.7159 - loss: 0.5792 - val_accuracy: 0.7357 - val_loss: 0.5578
Epoch 22/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.7145 - loss: 0.5828 - val_accuracy: 0.7357 - val_loss: 0.5556
Epoch 23/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.7221 - loss: 0.5750 - val_accuracy: 0.7357 - val_loss: 0.5569
Epoch 24/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7182 - loss: 0.5758 - val_accuracy: 0.7355 - val_loss: 0.5569
Epoch 25/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.7217 - loss: 0.5785 - val_accuracy: 0.7357 - val_loss: 0.5579
Epoch 26/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.7215 - loss: 0.5800 - val_accuracy: 0.7372 - val_loss: 0.5561
Epoch 27/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step - accuracy: 0.7230 - loss: 0.5752 - val_accuracy: 0.7367 - val_loss: 0.5569
Epoch 28/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.7169 - loss: 0.5819 - val_accuracy: 0.7370 - val_loss: 0.5572
Epoch 29/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.7189 - loss: 0.5776 - val_accuracy: 0.7355 - val_loss: 0.5565
Epoch 30/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 395us/step - accuracy: 0.7205 - loss: 0.5756 - val_accuracy: 0.7357 - val_loss: 0.5572
Epoch 31/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - accuracy: 0.7264 - loss: 0.5743 - val_accuracy: 0.7370 - val_loss: 0.5563
Epoch 32/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.7229 - loss: 0.5749 - val_accuracy: 0.7372 - val_loss: 0.5561
Epoch 33/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.7223 - loss: 0.5731 - val_accuracy: 0.7375 - val_loss: 0.5557
Epoch 34/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7260 - loss: 0.5729 - val_accuracy: 0.7377 - val_loss: 0.5563
Epoch 35/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7184 - loss: 0.5761 - val_accuracy: 0.7367 - val_loss: 0.5562
Epoch 36/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 476us/step - accuracy: 0.7286 - loss: 0.5722 - val_accuracy: 0.7375 - val_loss: 0.5569
Epoch 37/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.7215 - loss: 0.5779 - val_accuracy: 0.7375 - val_loss: 0.5551
Epoch 38/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.7182 - loss: 0.5787 - val_accuracy: 0.7372 - val_loss: 0.5561
Epoch 39/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.7205 - loss: 0.5775 - val_accuracy: 0.7367 - val_loss: 0.5546
Epoch 40/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.7264 - loss: 0.5741 - val_accuracy: 0.7370 - val_loss: 0.5553
Epoch 41/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.7192 - loss: 0.5770 - val_accuracy: 0.7367 - val_loss: 0.5550
Epoch 42/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.7206 - loss: 0.5759 - val_accuracy: 0.7372 - val_loss: 0.5561
Epoch 43/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - accuracy: 0.7266 - loss: 0.5679 - val_accuracy: 0.7365 - val_loss: 0.5554
Epoch 44/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.7236 - loss: 0.5721 - val_accuracy: 0.7360 - val_loss: 0.5542
Epoch 45/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7202 - loss: 0.5721 - val_accuracy: 0.7367 - val_loss: 0.5550
Epoch 46/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7209 - loss: 0.5698 - val_accuracy: 0.7362 - val_loss: 0.5561
Epoch 47/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.7263 - loss: 0.5699 - val_accuracy: 0.7362 - val_loss: 0.5560
Epoch 48/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.7209 - loss: 0.5735 - val_accuracy: 0.7362 - val_loss: 0.5551
Epoch 49/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.7198 - loss: 0.5770 - val_accuracy: 0.7360 - val_loss: 0.5548
Epoch 50/75

680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.7234 - loss: 0.5687 - val_accuracy: 0.7360 - val_loss: 0.5555
Epoch 51/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.7224 - loss: 0.5702 - val_accuracy: 0.7357 - val_loss: 0.5547
Epoch 52/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.7187 - loss: 0.5749 - val_accuracy: 0.7357 - val_loss: 0.5547
Epoch 53/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7287 - loss: 0.5625 - val_accuracy: 0.7357 - val_loss: 0.5563
Epoch 54/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7223 - loss: 0.5712 - val_accuracy: 0.7357 - val_loss: 0.5565
Epoch 55/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.7233 - loss: 0.5690 - val_accuracy: 0.7357 - val_loss: 0.5549
Epoch 56/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7277 - loss: 0.5684 - val_accuracy: 0.7357 - val_loss: 0.5559
Epoch 57/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - accuracy: 0.7306 - loss: 0.5663 - val_accuracy: 0.7360 - val_loss: 0.5559
Epoch 58/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7262 - loss: 0.5681 - val_accuracy: 0.7360 - val_loss: 0.5559
Epoch 59/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.7266 - loss: 0.5692 - val_accuracy: 0.7360 - val_loss: 0.5561
Epoch 60/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.7244 - loss: 0.5679 - val_accuracy: 0.7362 - val_loss: 0.5555
Epoch 61/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7256 - loss: 0.5701 - val_accuracy: 0.7360 - val_loss: 0.5553
Epoch 62/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7289 - loss: 0.5647 - val_accuracy: 0.7360 - val_loss: 0.5555
Epoch 63/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7318 - loss: 0.5623 - val_accuracy: 0.7365 - val_loss: 0.5561
Epoch 64/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.7204 - loss: 0.5701 - val_accuracy: 0.7367 - val_loss: 0.5548
Epoch 65/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.7216 - loss: 0.5699 - val_accuracy: 0.7367 - val_loss: 0.5548
Epoch 66/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.7259 - loss: 0.5701 - val_accuracy: 0.7365 - val_loss: 0.5556
Epoch 67/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.7258 - loss: 0.5677 - val_accuracy: 0.7360 - val_loss: 0.5549
Epoch 68/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.7237 - loss: 0.5711 - val_accuracy: 0.7365 - val_loss: 0.5549
Epoch 69/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7252 - loss: 0.5640 - val_accuracy: 0.7365 - val_loss: 0.5544
Epoch 70/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7276 - loss: 0.5666 - val_accuracy: 0.7365 - val_loss: 0.5555
Epoch 71/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.7254 - loss: 0.5698 - val_accuracy: 0.7362 - val_loss: 0.5545
Epoch 72/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.7286 - loss: 0.5683 - val_accuracy: 0.7360 - val_loss: 0.5545
Epoch 73/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7223 - loss: 0.5701 - val_accuracy: 0.7362 - val_loss: 0.5538
Epoch 74/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7249 - loss: 0.5718 - val_accuracy: 0.7365 - val_loss: 0.5534
Epoch 75/75
680/680 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - accuracy: 0.7302 - loss: 0.5648 - val_accuracy: 0.7360 - val_loss: 0.5550

In [396]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 436us/step - accuracy: 0.7292 - loss: 0.5602
Loss: 0.5602218508720398, Accuracy: 0.7292128205299377

In [369]:
# Export our model to HDF5 file
# I'm not exporting because it is not optimized yet.

Adam optimizer: 0.7304956316947937
RMSprop optimizer: 0.7310787439346313
SGD optimizer with 75 epochs, learning rate 0.01:  0.7331778407096863
SGD optimizer with 75 epochs, learning rate 0.005: 0.7325947284698486